### ISSUE TITLE
Support for .bedpe tracks

### ISSUE THREAD

**Issue by chrkouts** [gladkia/igvR#12]
Dear @paul-shannon,

Thank you for your great work! 
I would like to ask if you plan to include .bedpe tracks as well.
That would be very helpful with visualising Hi-C interaction loops.

Many thanks in advance for your help!
Christina Koutsothanasi

**Comment by paul-shannon** [comment]
Hi Christina,

Working on this now - it is taking a little longer than I anticipated.

I see that the example you gave, GM12828, also used by Jim Robinson and the igv.js developers, has only 6 columns - a good minimum, of course, in that chrom1, start1, end1, and chrom2, start2, end2 establishes the basics.

At bedtools.readthedocs.io/en/latest/content/general-usage.html they claim that a “typical” bedpe file looks like this:

   chr1  100   200   chr5  5000  5100  bedpe_example1  30   +  -
   chr9  1000  5000  chr9  3000  3800  bedpe_example2  100  +  -

Have you any thoughts on this?   Imagine that igv.js will handle both (and other) legal forms.  I will test with these two forms at least.

Let me know what you think.

 - Paul

**Comment by paul-shannon** [comment]
@chrkouts  - Hi Christine,

igvR version 1.7.10 has an early version of the BedpeInteractionsTrack.  Only the ````data.frame```` constructor for now: no http uri yet.  Give this a try: I welcome feedback.
I will try to add the url constructor over the weekend.
- Paul
From the man page:
````
         #----------------------------
         #  first, from a local file
         #----------------------------
     
       file <- system.file(package="igvR", "extdata", "sixColumn-demo1.bedpe")
       tbl.bedpe <- read.table(file, sep="\t", as.is=TRUE, header=TRUE)
       dim(tbl.1)  #  32 6
       track <- BedpeInteractionsTrack("bedpe-6", tbl.1)
     
         #------------------------------------------
         #  show the relevant portion of the genome
         #------------------------------------------
     
       shoulder <- 10000
       roi <- with(tbl, sprintf("%s:%d-%d", chrom1[1], min(start1)-shoulder, max(end2) + shoulder)))
       showGenomicRegion(igv, roi)
     
       displayTrack(igv, track)
````

**Comment by chrkouts** [comment]
Dear Paul,

Thank you for you quick response, I really appreciate your help.
I downloaded the new version and it works!
As you said on igv.js handle both types of bedpe files. 
As for the 10 columns bedpe I can just convert the data.frame to a six columns one, before calling the BedpeInteractionsTrack function.

Thank you again for your help.
Christina
