### ISSUE TITLE
show|hide track labels

### ISSUE THREAD

**Issue by paul-shannon** [gladkia/igvR#14]
@alessandriLuca proposes:

is there any way in which i can disable track labels? From the browser i can unselect the option but i wasnt able to find anything related to that in the igvR code.

**Comment by paul-shannon** [comment]
@alessandriLuca
I added one method to igvR, version 1.13.5:
```
showTrackLabels,igvR-method        package:igvR        R Documentation
Hide or show igv track labels
Description:
     Hide or show igv track labels
Usage:
     ## S4 method for signature 'igvR'
     showTrackLabels(obj, newState)
Arguments:
     obj: An object of class igvR
newState: logigal, either TRUE or FALSE
```

**Comment by alessandriLuca** [comment]
That's perfect!! 

Thank you again for your work ;). How can i cite you in the paper using igvR in my works?

**Comment by paul-shannon** [comment]
I believe this is the usual approach:

  from within R, enter citation("igvR”)

Glad you find the package useful!
