### ISSUE TITLE
Error: no slot of name "alignementj" for this object of class "GenomicAlignmentTrack"

### ISSUE THREAD

**Issue by genec1** [gladkia/igvR#16]
When I try to display a bam alignment track, I get the following error:

```
Error in sprintf("   writing bam file of size %d to %s", length(track@alignementj),  : 
  no slot of name "alignementj" for this object of class "GenomicAlignmentTrack"
```

`R/igvR.R` is the only file in which "alignementj" appears.  Examining the slot names for the GenomicAlignmentTrack object, the closest is "alignment".  The temporary fix is to set igv@quiet to TRUE, causing this code block to be skipped.

**Comment by paul-shannon** [comment]
@genec1  typo fixed.  Thank you for the bug report.
