### ISSUE TITLE
example(GWASTrack) broken

### ISSUE THREAD

**Issue by paul-shannon** [gladkia/igvR#20]
incorrect chrom.col, pos.col. pval.col
poor choice of sample data

updated code:
```
file <- system.file(package="igvR", "extdata", "gwas-5k.tsv")
tbl.gwas <- read.table(file, sep="\t", header=TRUE, quote="")
dim(tbl.gwas)
track <- GWASTrack("gwas 5k", tbl.gwas, chrom.col=12, pos.col=13, pval.col=28)
```

**Comment by paul-shannon** [comment]
@vjcitn  example(GWASTrack), with new data, now fixed in ```1.17.23```

**Comment by vjcitn** [comment]
Yes, looks great.  Consider using if (interactive()) instead of \dontrun for example(GWASTrack), I think the whole example would work fine interactively.

**Comment by paul-shannon** [comment]
```example(function)``` is an R package feature I have rarely used.   I now see its utility.  

```@examples``` for GWASTrack and half a dozen other tracks are now updated to run ```if(interactive())``` in 1.17.24. 
   
I will update the other classes also.  

thanks for this tip - I'm glad to have other eyes on this.

**Comment by paul-shannon** [comment]
completed some months ago
