### ISSUE TITLE
unify igvR and igvShiny removeTracksByName signature

### ISSUE THREAD

**Issue by paul-shannon** [gladkia/igvR#23]
@vjcitn @stankiewicz565

Vince and Sara, 

This may not be an easy fix, since igvR is an S4 object, and igvShiny is only functions.  

in igvR/igvR.R:
```
removeTracksByName(igv, trackNames)             # an S4 method
```
in igvShiny:
```
removeTracksByName(session, id, trackNames)  # a simple function
```

**Comment by vjcitn** [comment]
Can't the S4 method have a three argument signature and dispatch properly for the two packages?  Or you could use "ANY" for the second parameter of the S4 method and then test for classes of function inputs.

**Comment by vjcitn** [comment]
I can take a shot at this if we are agreed that both packages are in their mature state for now.  I would then fork both and try to do the mods.

**Comment by paul-shannon** [comment]
That would be most welcome, Vince.   Thank you!
