### ISSUE TITLE
Give access to .Rproj file

### ISSUE THREAD

**Issue by vladimirobucina** [gladkia/igvR#25]
Hi Paul, thank you very much for this package, I'm planning on using it to create IGV Shiny app. I wanted to ask you is it possible to give access to .Rproj file of the project, because it's more convenient to work that way? I can see it's not present on the repo. Maybe there is specific reason for that?

**Comment by paul-shannon** [comment]
Hi @vladimirobucina,

You might want to take a look at https://github.com/paul-shannon/igvShiny before embarking on a new igv shiny app.
Contributions, bug reports, PRs, forks - all welcome

**Comment by paul-shannon** [comment]
Sorry, @vladimirobucina, there is no .Rproj file for the package.   That's  RStudio-specific, I believe, which I rarely uses.

Instead, you might want to study (and use) the makefile.

**Comment by vladimirobucina** [comment]
Hi @paul-shannon I'll have a look at igvShiny :) I think people are more used to using .Rproj file, because most of R developers use RStudio IDE, but thank you for your suggestion, makefile might be a better solution. I'll probably create few PRs in next few weeks.
