### ISSUE TITLE
Add jsonlite to getSupportedGenomes method

### ISSUE THREAD

**Issue by vladimirobucina** [gladkia/igvR#26]
If someone is using `rjson`  library as a default for `fromJSON` function this line of code won't work:
https://github.com/paul-shannon/igvR/blob/26e99bdbe054e3c005d24745a090c6c3cc944e0b/R/igvR.R#L319

It should say:
`tbl.genomes <- jsonlite::fromJSON(current.genomes.raw)`

**Comment by gladkia** [comment]
Hi @vladimirobucina. Thanks for the suggestion.
FYI, igvR uses wrapper of `fromJSON ` with `auto_unbox` set by default to TRUE ([link1](https://github.com/gladkia/igvR/blob/master/NAMESPACE#L57), [link2](https://github.com/gladkia/BrowserViz/blob/master/NAMESPACE#L7)). More details can be found [here](https://github.com/gladkia/BrowserViz/blob/master/R/BrowserViz-class.R#L734-L757).
