### ISSUE TITLE
Segmented Copy Number Track

### ISSUE THREAD

**Issue by fulviodan13** [gladkia/igvR#28]
Hi Paul,

Could be possible to add a function for copy number seg file visualization through igvR?

Thank you!

Fulvio

**Comment by paul-shannon** [comment]
@fulviodan13 - Hi Fulvio,

Just last week I retired from bioinformatics.  So, with regret, I cannot help out on this.
I am working on transferring the package to someone else in Bioconductor.  Maybe @vjcitn, who has a recent fork:

 https://github.com/vjcitn/igvR

I don't know if it is appropriate for me to recommend this, so please step cautioulsy:  Perhaps you could put your request to him?   And best of all, offer a PR which contributes to a solution?

 - Paul

**Comment by fulviodan13** [comment]
Thank you, Paul.
