### ISSUE TITLE
is it possible to move the track names to the side instead of on the track?

### ISSUE THREAD

**Issue by duleise** [gladkia/igvR#7]
even thought “hide track name” is an option, when i do want to show it, in some cases the name is covering the leftmost part of the track. 
it would be nice to move the name outside of the track area. it would be nicer if they can be right aligned. 
great package and clear vignette. 
thank you.

**Comment by paul-shannon** [comment]
@duleise So sorry for this ridiculously late reply!   
I'm afraid that this display policy, for track names, is set by Jim Robinson in igv.js.
If you can persuade him to add this flexibility I will certainly support it in igvR.
Sorry I cannot be more directly helpful.
