### ISSUE TITLE
Is it possible to save the results automatically?

### ISSUE THREAD

**Issue by pgasperowicz** [gladkia/igvR#8]
@paul-shannon 
Hi!
I would like to save localhost to *.png or *.svg. The recorded image should contain all the displayed information: navigation panel, chromosome image, refseq, all tracks. Best solution would be to make a screenshoot.

I tried the `webshot` package but unfortunately it does not recognize localhost. I also tried to import the content back to Rstudio Viewer Pane but nothing came of it either. 

I know that you can save each track by RMB on a given track and save as * .png or * .svg. but it's about saving it automatically after being generated.

  Best!

**Comment by paul-shannon** [comment]
@pioters Good suggestion.   It's a busy week so I may not get to this till the weekend.  But get to it I will!

**Comment by paul-shannon** [comment]
@pioters  It took me longer to get around to this than I predicted.   But save to svg is now supported:
  
   - Version 1.5.10
   - ````saveToSVG(igv, filename)````

Let me know if it does what you need.

**Comment by pgasperowicz** [comment]
Awsome! I'll get to it at the weekend.

**Comment by pgasperowicz** [comment]
Perfect. Works like a charm. Thank you!
